Scanner daniel (#9)
* Added a brief description in the comment.

* files for further development added

* libraries included

* errors added

* errors added

* added prototypes of functions

* further instructions added. error.h complete.
TODO: enums, graph!! and buffer

* token types

* added buffer library file

* added main function for testing purposes

* added main function for testing purposes

* added further simple states

* todo fix lower and greater

* fixed lower and greater + fixed including libraries

* buffer.h completed

* added doxygen comments to scanner.h

* buffer.c implemented

* buffer.c implemented - details changed

* buffer.c implemented - details changed

* buffer.c implemented - details changed

* further implementation of fsm, comments, prolog, lf + whitespace

* completed finite state machines states, in string processing is missing hexadecimal+octal convert to decimal

* octal processing added

* octal processing added

* bug fix

* in function `convertOctalToDecimal':
scanner.c:(.text+0x2ef): undefined reference to `pow'

* compiled without state hex and state octal

* tested: keywords, signs, float, integers
to be tested: hexa and octal characters, comments, prolog and question mark
issue in buffer fixed
removing debug comments needed!!!

* tested: keywords, signs, float, integers, prolog  and question mark, variables, comments

to be tested: hexa and octal characters
removing debug comments needed!!!
check float and int

* tested: keywords, signs, float, integers, prolog  and question mark, variables, comments, comma, semicolon, strings

to be tested: hexa and octal characters
removing debug comments needed!!!
check float and int

* Library file for token_struct is ready to use

* token_buffer.c added, ready for implementation

* names of token with question mark

* -added new types of tokens for syntactical analysis
-token buffer implemented(testing needed)
-syntactic_stack.h added, header file for syntactical bottom up analysis

* -added new types of tokens for syntactical analysis
-token buffer implemented(testing needed)
-syntactic_stack.h added, header file for syntactical bottom up analysis

Co-authored-by: Samuel Simun <samuelsimun@gmail.com>